[package]
name = "aws-mfa"
version = "0.1.0"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1"
rusoto_iam = "0.36"
rusoto_sts = "0.36"
tokio-core = "0.1"
tokio-process = "0.2"
